require: rubocop-rspec

AllCops:
  DisplayCopNames: true

LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false
